### ISSUE TITLE
Protect secrets variables with Github Actions

### ISSUE THREAD

**Issue by Azlou77** [Azlou77/JS-Node-projects#51]
**Link:**
[NodeJs Github Actions](nodejs/github-actions)

1. Create build.js
```// build.js
    console.log(`Hello ${process.env.HELLO}`)
```
2. Create package.json 
   
``` {
    "scripts": {
      "build": "node build.js"
    }
  }
```
3. Create Github Action file

```
name: npm run build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

```
4. Install dotenv
`npm install dotenv --save`
5. Create .env file
6. Set build.js
```
// build.js
require('dotenv').config()
console.log(process.env) // remove this after you've confirmed it is working

console.log(`Hello ${process.env.HELLO}`)
```
7. Run file  build js
8. Results expectud: Hello world

![Image](https://github.com/Azlou77/JS-Node-projects/assets/69016056/26e72d92-2f14-4e72-82f4-e7ac5d7b8456)
